//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageEditor.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageEditor.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Apply.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save package.
        /// </summary>
        internal static string cannotSave {
            get {
                return ResourceManager.GetString("cannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will take effect on next program restart..
        /// </summary>
        internal static string changesWillTakeEffectOnNextStart {
            get {
                return ResourceManager.GetString("changesWillTakeEffectOnNextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changes will be lost. Discard changes?.
        /// </summary>
        internal static string discardChanges {
            get {
                return ResourceManager.GetString("discardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display menu.
        /// </summary>
        internal static string displayMenu {
            get {
                return ResourceManager.GetString("displayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full acces.
        /// </summary>
        internal static string fullAccess {
            get {
                return ResourceManager.GetString("fullAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolated.
        /// </summary>
        internal static string isolated {
            get {
                return ResourceManager.GetString("isolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu requires at least two programs..
        /// </summary>
        internal static string menuRequiresAtLeastTwo {
            get {
                return ResourceManager.GetString("menuRequiresAtLeastTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu requires at least two programs. Transform into a command?.
        /// </summary>
        internal static string menuRequiresAtLeastTwoTransform {
            get {
                return ResourceManager.GetString("menuRequiresAtLeastTwoTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        internal static string opening {
            get {
                return ResourceManager.GetString("opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening package.
        /// </summary>
        internal static string openingPackage {
            get {
                return ResourceManager.GetString("openingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package successfully built in:.
        /// </summary>
        internal static string packageBuiltOk {
            get {
                return ResourceManager.GetString("packageBuiltOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package saved.
        /// </summary>
        internal static string packageSaved {
            get {
                return ResourceManager.GetString("packageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving package.
        /// </summary>
        internal static string savingPackage {
            get {
                return ResourceManager.GetString("savingPackage", resourceCulture);
            }
        }
    }
}
